dist: trusty
sudo: false

language: java

jdk:
  - oraclejdk8

script: .travis/script.sh

after_success: .travis/after_success.sh

deploy:
  provider: releases
  api_key:
    secure: Ym5jN3kO9O/zn9RYHBbApLw+Sajz+dz7lA2uD+PwXYbsta/fW/4zTtZ+53621SbEhyrWwC6Y0i6jmeME1Qf2TwOxOh+gdXBm50DgxNOMMFuS8sp53yAokEHnGbC0q76k1K+zu4tBcSCAbnxafFhta9m7MNvhCuGhYpyTpTMdg4WecieCvWp6TdVRI9J05jjxWkiRkuBScFsJER4aYqxIilJzRuIQ/UyMzWM3FndczJP2AGwsX8BN6TF8PzGiuAedovBjQp8stLq6oWuLEHz6rHeAmEZo9sTle4T+R/fJlRs8/vmH5JONahLaim7uSr4EULHRIM9gdX5ZGkXIEGjsV1Pdc0G4LBq+MCEHRiOh34Jp+SjdKE0HKHssQC4+XT2Wip/GxTQw+QfaILmzTvNp6vZT4YqlFErVU5V7n1pz0nw8DbwWHfAmiaYHREUiUSLv//XCcGN7nUKGWbhBEQrmKzQNYijnvbNk7YtTpzZ92kjIWKOzIQ4/5IAuvQ+TsAKK2x+iKpSj/gNoc9oI63WZciMG99kQdPTshzipgUeC97tOaQZyftsEY3bX9PS1w+obxPrQMzqb9mgDm/nBivMBmJskeG3u6EN2N62XxBm0xFARzfo09U8o3TnRd6mBrLFbNoTn0x2q/GW088vp+oAozkSXvMboRlE/f6tBDAHsA/s=
  file:
    - build/distributions/packt4free-${TRAVIS_TAG}.tar
    - build/distributions/packt4free-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: madhead/packt4free
    tags: true
